name: Test Examples

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Example 1
      run: |
        cd examples/example1
        python run_example1.py

    - name: Run Example 2
      run: |
        cd examples/example2
        python run_example2.py

    - name: Run Example 3
      run: |
        cd examples/example3
        python run_example3.py
